# 变量./.env文件中的
version: '3'
services:
  mysql:
    container_name: test_mysql        # 指定容器的名称
    build:
      context: .
      dockerfile: mysql.build
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    volumes:
      - "${MYSQL_DOCKER_DIR}/data:/var/lib/mysql"  # 挂载数据目录,便于备份,重新构建时候数据目录先删掉，启动会自动创建
      - "${MYSQL_DOCKER_DIR}/conf:/etc/mysql/conf.d/"      # 挂载配置文件目录